{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[{"file_id":"1P43VCI2OUXTw8qdnUqbCe4xcPwAJGgH3","timestamp":1728083449004}]},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["*   **Año:** Primer año\n","*   **Alumno/a:** Iaizzo Stefano\n","*   **Legajo:** 42255420"],"metadata":{"id":"UwxQU5JCF33j"}},{"cell_type":"markdown","source":["# Pydantic\n","Pydantic es una libreria rapida y extensible que nos permite validar datos usando tipos de datos de Python.\n"],"metadata":{"id":"8ec8DQdbWQfC"}},{"cell_type":"markdown","source":["Primero, importe `pydantic`."],"metadata":{"id":"uF01w4AQcrtV"}},{"cell_type":"code","source":["import pydantic"],"metadata":{"id":"4WPUcwU_c5n2","executionInfo":{"status":"ok","timestamp":1728083499182,"user_tz":180,"elapsed":338,"user":{"displayName":"Stefano Iaizzo","userId":"18204087347266255614"}}},"execution_count":1,"outputs":[]},{"cell_type":"markdown","source":["Supongamos que tenemos una lista de clientes (llamemoslo en el codigo `Client`). Los clientes tienen dos campos: DNI (un entero) y nacionalidad (un `string`). Cree el modelo base de `Client` (en forma de clases de Python)."],"metadata":{"id":"eC8fpbQ04GzX"}},{"cell_type":"code","source":["class Cliente(pydantic.BaseModel):\n","  dni: int\n","  nacionalidad: str"],"metadata":{"id":"I4zJ7s_k4GkI","executionInfo":{"status":"ok","timestamp":1728083580109,"user_tz":180,"elapsed":300,"user":{"displayName":"Stefano Iaizzo","userId":"18204087347266255614"}}},"execution_count":7,"outputs":[]},{"cell_type":"markdown","source":["Cree a un usuario con documento 39.755.010 y nacionalidad 'Argentina'. Muestre todos sus campos."],"metadata":{"id":"zas-XX4r4SeP"}},{"cell_type":"code","source":["usuario = Cliente(dni = 39755010, nacionalidad = 'Argentina')\n","print(usuario)"],"metadata":{"id":"_DhtCWhr4ST9","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1728083582924,"user_tz":180,"elapsed":329,"user":{"displayName":"Stefano Iaizzo","userId":"18204087347266255614"}},"outputId":"4001682f-4174-455d-899d-d8c54174f2ec"},"execution_count":8,"outputs":[{"output_type":"stream","name":"stdout","text":["dni=39755010 nacionalidad='Argentina'\n"]}]},{"cell_type":"markdown","source":["Intente crear al usuario con un documento en forma de `string`. Deberia fallar..."],"metadata":{"id":"ejbn5RSH4S_W"}},{"cell_type":"code","source":["usuario = Cliente(dni = '39755010', nacionalidad = 'Argentina')"],"metadata":{"id":"OMPq8C1C4Su3","executionInfo":{"status":"ok","timestamp":1728083584395,"user_tz":180,"elapsed":307,"user":{"displayName":"Stefano Iaizzo","userId":"18204087347266255614"}}},"execution_count":9,"outputs":[]},{"cell_type":"markdown","source":["Hemos detectado que ciertos clientes tienen nacionalidades que no existen. Ademas, hay numeros de documento negativos y se tiene que poder agregar la fecha de registro de los clientes (que no pueden ser del futuro). Cambiar la definicion del cliente para que estas cosas no ocurran. Despues de la siguiente celda, cree otras 3 mas probando un caso donde deberia funcionar y otros dos en los que no."],"metadata":{"id":"jARZRMfe6MPE"}},{"cell_type":"code","source":["class Cliente(pydantic.BaseModel):\n","    dni: conint(ge=0)\n","    nacionalidad: constr(min_length=1)\n","    fecha_registro: datetime\n","\n","usuario_valido = Cliente(dni=12345678, nacionalidad='Argentina', fecha_registro='2024-10-01')"],"metadata":{"id":"JWsWZZPH6NFv","executionInfo":{"status":"ok","timestamp":1728084773138,"user_tz":180,"elapsed":322,"user":{"displayName":"Stefano Iaizzo","userId":"18204087347266255614"}}},"execution_count":37,"outputs":[]},{"cell_type":"code","source":["usuario_invalido = Cliente(dni=-12345678, nacionalidad='Argentina', fecha_registro='2024-10-01')"],"metadata":{"id":"sWyLaqoC7QUK","colab":{"base_uri":"https://localhost:8080/","height":323},"executionInfo":{"status":"error","timestamp":1728084775085,"user_tz":180,"elapsed":307,"user":{"displayName":"Stefano Iaizzo","userId":"18204087347266255614"}},"outputId":"816579ea-eb56-4175-ec46-71a10f60453d"},"execution_count":38,"outputs":[{"output_type":"error","ename":"ValidationError","evalue":"1 validation error for Cliente\ndni\n  Input should be greater than or equal to 0 [type=greater_than_equal, input_value=-12345678, input_type=int]\n    For further information visit https://errors.pydantic.dev/2.9/v/greater_than_equal","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValidationError\u001b[0m                           Traceback (most recent call last)","\u001b[0;32m<ipython-input-38-66019b485175>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0musuario_invalido\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mCliente\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdni\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m-\u001b[0m\u001b[0;36m12345678\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnacionalidad\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'Argentina'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfecha_registro\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'2024-10-01'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/pydantic/main.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, **data)\u001b[0m\n\u001b[1;32m    210\u001b[0m         \u001b[0;31m# `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    211\u001b[0m         \u001b[0m__tracebackhide__\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 212\u001b[0;31m         \u001b[0mvalidated_self\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__pydantic_validator__\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mvalidate_python\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself_instance\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    213\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mvalidated_self\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    214\u001b[0m             warnings.warn(\n","\u001b[0;31mValidationError\u001b[0m: 1 validation error for Cliente\ndni\n  Input should be greater than or equal to 0 [type=greater_than_equal, input_value=-12345678, input_type=int]\n    For further information visit https://errors.pydantic.dev/2.9/v/greater_than_equal"]}]},{"cell_type":"code","source":["usuario_valido = Cliente(dni=12345678, nacionalidad='', fecha_registro='2024-10-01')"],"metadata":{"id":"E6h_7zb77QhN","colab":{"base_uri":"https://localhost:8080/","height":323},"executionInfo":{"status":"error","timestamp":1728084778610,"user_tz":180,"elapsed":327,"user":{"displayName":"Stefano Iaizzo","userId":"18204087347266255614"}},"outputId":"744d949a-4b0c-4530-f7d2-1e89a1e49c51"},"execution_count":39,"outputs":[{"output_type":"error","ename":"ValidationError","evalue":"1 validation error for Cliente\nnacionalidad\n  String should have at least 1 character [type=string_too_short, input_value='', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.9/v/string_too_short","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValidationError\u001b[0m                           Traceback (most recent call last)","\u001b[0;32m<ipython-input-39-9793a4e4abb9>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0musuario_valido\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mCliente\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdni\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m12345678\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnacionalidad\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m''\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfecha_registro\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'2024-10-01'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/pydantic/main.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, **data)\u001b[0m\n\u001b[1;32m    210\u001b[0m         \u001b[0;31m# `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    211\u001b[0m         \u001b[0m__tracebackhide__\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 212\u001b[0;31m         \u001b[0mvalidated_self\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__pydantic_validator__\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mvalidate_python\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself_instance\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    213\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mvalidated_self\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    214\u001b[0m             warnings.warn(\n","\u001b[0;31mValidationError\u001b[0m: 1 validation error for Cliente\nnacionalidad\n  String should have at least 1 character [type=string_too_short, input_value='', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.9/v/string_too_short"]}]},{"cell_type":"code","source":["!pip install pandera"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"FaSKS1uO7pzx","executionInfo":{"status":"ok","timestamp":1728085686141,"user_tz":180,"elapsed":5576,"user":{"displayName":"Stefano Iaizzo","userId":"18204087347266255614"}},"outputId":"69dbbe9e-3bb0-4c43-cb24-b8cdc63930a2"},"execution_count":44,"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting pandera\n","  Downloading pandera-0.20.4-py3-none-any.whl.metadata (15 kB)\n","Collecting multimethod<=1.10.0 (from pandera)\n","  Downloading multimethod-1.10-py3-none-any.whl.metadata (8.2 kB)\n","Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from pandera) (1.26.4)\n","Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from pandera) (24.1)\n","Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from pandera) (2.2.2)\n","Requirement already satisfied: pydantic in /usr/local/lib/python3.10/dist-packages (from pandera) (2.9.2)\n","Requirement already satisfied: typeguard in /usr/local/lib/python3.10/dist-packages (from pandera) (4.3.0)\n","Collecting typing-inspect>=0.6.0 (from pandera)\n","  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)\n","Requirement already satisfied: wrapt in /usr/local/lib/python3.10/dist-packages (from pandera) (1.16.0)\n","Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->pandera) (2.8.2)\n","Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->pandera) (2024.2)\n","Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->pandera) (2024.2)\n","Collecting mypy-extensions>=0.3.0 (from typing-inspect>=0.6.0->pandera)\n","  Downloading mypy_extensions-1.0.0-py3-none-any.whl.metadata (1.1 kB)\n","Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.10/dist-packages (from typing-inspect>=0.6.0->pandera) (4.12.2)\n","Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic->pandera) (0.7.0)\n","Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic->pandera) (2.23.4)\n","Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pandera) (1.16.0)\n","Downloading pandera-0.20.4-py3-none-any.whl (259 kB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m259.6/259.6 kB\u001b[0m \u001b[31m5.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading multimethod-1.10-py3-none-any.whl (9.9 kB)\n","Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)\n","Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)\n","Installing collected packages: mypy-extensions, multimethod, typing-inspect, pandera\n","Successfully installed multimethod-1.10 mypy-extensions-1.0.0 pandera-0.20.4 typing-inspect-0.9.0\n"]}]},{"cell_type":"code","source":["usuario_valido = Cliente(dni=12345678, nacionalidad='Argentina', fecha_registro='2025-10-01')"],"metadata":{"id":"MtDGMxri7R_O","executionInfo":{"status":"ok","timestamp":1728084781605,"user_tz":180,"elapsed":319,"user":{"displayName":"Stefano Iaizzo","userId":"18204087347266255614"}}},"execution_count":40,"outputs":[]},{"cell_type":"markdown","source":["# Pandera\n","Hacer lo que se pidio en la ultima celda anterior, pero con Pandera."],"metadata":{"id":"79P3MNuZ8-t3"}},{"cell_type":"code","source":["import pandas as pd\n","import pandera as pa\n","from datetime import date\n","\n","\n","client_schema = pa.DataFrameSchema(\n","    columns={\n","        \"dni\": pa.Column(int, checks=pa.Check(lambda s: s >= 0)),\n","        \"nacionalidad\": pa.Column(str),\n","        \"fecha_registro\": pa.Column(pa.DateTime)\n","    },\n","    strict=True,\n",")\n","\n","\n"],"metadata":{"id":"z3DJDdci8-BP","executionInfo":{"status":"ok","timestamp":1728088346100,"user_tz":180,"elapsed":288,"user":{"displayName":"Stefano Iaizzo","userId":"18204087347266255614"}}},"execution_count":66,"outputs":[]}]}